@startuml
!theme vibrant
top to bottom direction
skinparam linetype ortho

class AddVehicleController
class DataTransferService
class DatabaseContext {
  - vehicles: ObservableList<Vehicle>
  - instance: IDatabaseContext
  - dealers: ObservableList<Dealer>
   dealers: ObservableList<Dealer>
   vehicles: ObservableList<Vehicle>
   dealershipIDs: List<String>
   instance: IDatabaseContext
}
class Dealer {
  - name: String
  - enabledForAcquisition: boolean
  - dealershipId: String
  - vehicles: List<Vehicle>
   name: String
   dealershipId: String
   enabledForAcquisition: boolean
   observableVehicles: ObservableList<Vehicle>
   vehicles: List<Vehicle>
}
class DealerRepository {
   dealers: ObservableList<Dealer>
   dealershipIDs: List<String>
}
class DealerService {
   dealers: ObservableList<Dealer>
   dealershipIDs: List<String>
}
class DealersXMLModel {
  + dealers: List<Dealer>
   dealers: List<Dealer>
}
class DealershipDatabase {
  - database: List<Dealer>
   database: List<Dealer>
}
interface IDatabaseContext << interface >> {
   dealers: ObservableList<Dealer>
   dealershipIDs: List<String>
   vehicles: ObservableList<Vehicle>
}
interface IFileHandler << interface >>
class JsonHandler {
  - instance: JsonHandler
   instance: JsonHandler
}
class Logger {
   logger: Logger
}
class Main
class MainController {
   stage: Stage
}
class NotificationHandler
class Price {
  + price: double
  + currency: String
   currency: String
   price: double
}
class Result<T> {
  - success: boolean
  - data: T
  - errorMessage: String
   data: T
   success: boolean
   errorMessage: String
}
class ValidationException {
  - validationErrors: List<String>
   validationErrors: List<String>
}
class Vehicle {
  - manufacturer: String
  - type: String
  - vehicleId: String
  - acquisitionDate: Long
  - price: Price
  - dealershipName: String
  - dealershipId: String
  - model: String
   manufacturer: String
   type: String
   acquisitionDate: long
   price: Price
   dealershipName: String
   vehicleId: String
   formattedAcquisitionDate: String
   isRented: boolean
   dealershipId: String
   priceAsString: String
   model: String
   isRentedAsString: String
}
class VehicleRepository {
   vehicles: ObservableList<Vehicle>
}
class VehicleService {
   vehicles: ObservableList<Vehicle>
}
class XmlHandler {
  - instance: XmlHandler
   instance: XmlHandler
}

AddVehicleController  "1" *-[#595959,plain]-> "notificationHandler\n1" NotificationHandler
AddVehicleController  "1" *-[#595959,plain]-> "vehicleService\n1" VehicleService
DataTransferService   "1" *-[#595959,plain]-> "jsonHandler\n1" JsonHandler
DataTransferService   "1" *-[#595959,plain]-> "logger\n1" Logger
DataTransferService   "1" *-[#595959,plain]-> "notificationHandler\n1" NotificationHandler
DatabaseContext       "1" *-[#595959,plain]-> "dealers\n*" Dealer
DatabaseContext        -[#008200,dashed]-^  IDatabaseContext
DatabaseContext       "1" *-[#595959,plain]-> "instance\n1" IDatabaseContext
DatabaseContext       "1" *-[#595959,plain]-> "vehicles\n*" Vehicle
Dealer                "1" *-[#595959,plain]-> "vehicles\n*" Vehicle
DealerRepository      "1" *-[#595959,plain]-> "databaseContext\n1" IDatabaseContext
DealerService         "1" *-[#595959,plain]-> "repository\n1" DealerRepository
DealersXMLModel       "1" *-[#595959,plain]-> "dealers\n*" Dealer
DealershipDatabase    "1" *-[#595959,plain]-> "database\n*" Dealer
JsonHandler           "1" *-[#595959,plain]-> "databaseContext\n1" IDatabaseContext
JsonHandler            -[#008200,dashed]-^  IFileHandler
JsonHandler           "1" *-[#595959,plain]-> "logger\n1" Logger
Main                  "1" *-[#595959,plain]-> "logger\n1" Logger
MainController        "1" *-[#595959,plain]-> "dataTransferService\n1" DataTransferService
MainController        "1" *-[#595959,plain]-> "dealerService\n1" DealerService
MainController        "1" *-[#595959,plain]-> "jsonHandler\n1" JsonHandler
MainController        "1" *-[#595959,plain]-> "logger\n1" Logger
MainController        "1" *-[#595959,plain]-> "notificationHandler\n1" NotificationHandler
MainController        "1" *-[#595959,plain]-> "vehicleService\n1" VehicleService
Scene                  -[#595959,dashed]->  Dealer                : "«create»"
Scene                  -[#595959,dashed]->  Price                 : "«create»"
Scene                  -[#595959,dashed]->  Vehicle               : "«create»"
Vehicle               "1" *-[#595959,plain]-> "price\n1" Price
VehicleRepository     "1" *-[#595959,plain]-> "databaseContext\n1" IDatabaseContext
VehicleService        "1" *-[#595959,plain]-> "repository\n1" VehicleRepository
XmlHandler             -[#008200,dashed]-^  IFileHandler
XmlHandler            "1" *-[#595959,plain]-> "logger\n1" Logger
@enduml