@startuml
!theme cerulean

actor Manager
participant UI
participant MainController
participant AddVehicleController
participant Vehicle
participant VehicleService
participant VehicleRepository
participant DatabaseContext

== Manager Adds a Vehicle ==
note right of Manager
User has already input
the vehicle data into the dialog.
endnote

Manager -> UI: Clicks to Add Vehicle
UI -> MainController: Add Vehicle
MainController -> AddVehicleController: onAddVehicle()\nCalls AddVehicleController to \nadd the new vehicle
AddVehicleController -> Vehicle: Create Object Instance
Vehicle -> Vehicle: Validates itself
Vehicle -> AddVehicleController: Created Object/Throws an error
AddVehicleController -> VehicleService: Add Vehicle
VehicleService -> VehicleRepository: Add Vehicle
VehicleRepository -> DatabaseContext: Attempt to insert into database
DatabaseContext -> VehicleRepository: response
VehicleRepository -> VehicleService: response
VehicleService -> AddVehicleController: response
AddVehicleController -> UI: Notifies success/error.
UI -> Manager: Manager sees the notification pop up.

@enduml



