@startuml
!theme cerulean

actor Manager
participant UI
participant NotificationHandler
participant MainController
participant DataTransferService
participant FileChooser
participant XmlHandler
participant DatabaseContext

== Manager Imports XML Formatted File ==

Manager -> UI: Clicks on Import XML
UI -> MainController: Import XML Event
MainController -> DataTransferService: onImportXml()\nCalls DataTransferService\nto open file selector
DataTransferService -> FileChooser: Displays FileChooser class UI for .xml file selection
FileChooser -> UI: Displays UI for choosing .xml files
Manager -> UI: Selects an .xml file
UI -> FileChooser: .xml file is Selected
FileChooser -> DataTransferService: Provides the selected file
DataTransferService -> XmlHandler: Calls importXml() with the file
XmlHandler -> DatabaseContext: Calls importXml() to validate and attempt to add new \nDealers and their Vehicle data to database
XmlHandler -> DataTransferService: Return result of success/failure for the import
DataTransferService -> NotificationHandler: Handle result of success/failure for the import
NotificationHandler -> UI: Notify user of result
UI -> Manager: Reads notification pop up
@enduml