@startuml
'https://plantuml.com/sequence-diagram
'WIP
autonumber

actor Manager
participant UI
participant MainController
participant VehicleService
participant VehicleRepository
participant DatabaseContext
participant Vehicle

Manager -> UI: Selects vehicle to toggle rent status
UI -> MainController: Get vehicle information
MainController -> Vehicle: getType()
Vehicle -> MainController: returns getType()
MainController -> UI: If vehicle.getType() is "sports car", gray out button and make it unclickable


Manager -> UI: Clicks to toggle if a vehicle is rented
UI -> MainController: Toggle Rented
MainController -> VehicleService: toggleRented(Vehicle vehicle)
VehicleService -> VehicleRepository: toggleRented(Vehicle vehicle)
VehicleRepository -> DatabaseContext: toggleRented(Vehicle vehicle)
DatabaseContext -> Vehicle: toggleRented
MainController -> UI: update vehicle info
@enduml